# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8424eaf07056903233bd86a9a69ee72981fa3b6d6771797c4372e67a7bf427d51ddccaba928c549071e6fe9fe4cd0eb6cdf5433d32824ace13f0d06a663f986b

test:
  secret_key_base: 0c12bf02d25c196338fc66118dfdaa2633cdf995f5c63e1c40aaf9a0f8650f395e8d49f3b66ca201f8c5d639c083ea1cfb7294d67be5908ada42bc5c6d030255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
