# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 101a4c021b750aafc7c087052543f9dd20fac14f6c1d5b47dfe0a1fe11c6c03f0d10728d9f6ed6ca5413f3da907cdf7f68591ee4eeabdb1e11fab9944a507de3

test:
  secret_key_base: c20e636907d0936604bcaf6d79a4ff7a06ebf52b6f880fed90ae1a64ed1075c5166d24e2c2d34771d03d345cd118a73bfdccdd058caf2ffad0f85a09db2a6281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
