# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac2980299bdef024cd092c8d68ee82f89dac609126838133bf03e3fbbd5f24627ef006b50ba2c5fe366afde253dcbd1aab78ce7339c029ae53b3695b575222bc

test:
  secret_key_base: 3cd1bf18877ef6b818027c1dcbbfcbbe95681a0f3a8c5071d0b26a8ef45a323d89399a83792b790c0f9f2a5fca724fd99433a74d372b9a3a5e3fce3addc381d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
