# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbade97d10e4ddc177f712db63ce6f800be24a18bfdd646c76b2fbbd75957b063b67f63f4db5d686fa4c22968d7b94251ac186ce039932413e59d00bc389dc7b

test:
  secret_key_base: 7e312bec15bf618866d7fc78d97f06540f939cbd05990533f61932b8f0d0b7dcc36e514d980273f97d126019c43effad7a923226ee47d1382f579acd19c14089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
