# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 044d96c82d02560f3c67e08efc465ef4dcdaef6de244daa4a8fe63074b3c49f01f75c652aca87a0d199671392dfe8eb027055e9f8b3c30e9786e3639f6defe2c

test:
  secret_key_base: 0aeedd62f433a5831e403bb9d8228734f1f0a8b7d8670bf13ec697f343828f5336c437d03c3c67e698fd12a9d0ff983da72213bb2c0a14e0cbe190de3a160a73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
