namespace :morning do
  desc "Turn off the goddamn alarm"
  task :turn_off_alarm do
    puts "Turned off the alarm."
  end

  desc "Make yourself a fancy man"
  task :groom_self do
    puts "Brushed teeth."
    puts "Showered."
    puts "Combed beard."
  end

  desc "Return from the dead"
  task :make_coffee do
    cups = ENV['COFFEE_CUPS'] || 2
    puts "Made #{ cups } cups of coffee. Shakes are gone."
  end

  desc "Walk the horrible little dog"
  task :walk_dog do
    puts "Walked the horrible little dog."
  end

  desc "Perform all the morning tasks"
  task :get_ready => [:turn_off_alarm, :groom_self, :make_coffee, :walk_dog] do
    puts "All ready for a wonderful day as a corporate slave"
  end
end

task :default => 'morning:get_ready'

namespace :morning do
  task :groom_self do
    puts "Applied hairspray."
  end
end

namespace :afternoon do
  desc "Make special afternoon coffee"
  task :make_coffee do
    Rake::Task['morning:make_coffee'].invoke
    puts "Added vodka."
    puts "Ready for the afternoon."
  end
end
