# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7527491d3aa343c71418ee8814c6d6b82c475b0c0ab63e368bcb4a7091ab1b991c3415a2b1d3cbfd971ad90fe409bad2cc5f5b03fd6c0e2125d024f41e8462b

test:
  secret_key_base: 8ad392e38a94b45bc3d5f782e9501f9e43fda26da79363d750a6e16405ea2d04bb991a397dc76b7bc0e119c1ea1568bcb00cdaa3939d1b9dd2a237c9b78a8026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
